# https://utopian.io
# Development docker-compose.yml file.
#
# for customizations, prefer using docker-compose.override.yml.

# docker-compose version.
version: '3'

# named volumes definition.
volumes:
  # .config.
  dot-config:
  # .local.
  dot-local:
  # .cache.
  dot-cache:

# services definition.
services:
  # main application service.
  app:
    # use Node.js 10
    image: ambientum/node:10
    # start command.
    command: yarn run dev
    # map volumes
    volumes:
      # application folder.
      - .:/var/www/app
      # .config files.
      - dot-config:/home/ambientum/.config
      # .cache files.
      - dot-cache:/home/ambientum/.cache
      # .local files.
      - dot-local:/home/ambientum/.local
    # expose posts.
    ports:
      - 8080:8080
