# use NodeJS as language
language: node_js

# node version to use on builds (node vs iojs)
node_js:
  - node

# enable caching of directories.
cache:
  directories:
    - node_modules

# build script
script: npm run build

# pre deployment scripts.
before_deploy:
  # install firebase tools (cli).
  - npm install -g firebase-tools
  # enable the firebase project to be used for deployment.
  - firebase use --add $FIREBASE_DEPLOY_PROJECT_ID --alias default

## deployment stage.
deploy:
  # deploys to prod
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT_ID
  on:
    branch: master

  # deploys to dev
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  project: $FIREBASE_DEV_PROJECT_ID
  on:
    branch: develop
