# use NodeJS as language
language: node_js

# node version to use on builds (node vs iojs)
node_js:
  - node

# enable caching of directories.
cache:
  directories:
    - node_modules

# build script
script: npm run build

# pre deployment scripts.
before_deploy:
  # install firebase tools (cli).
  - npm install -g firebase-tools
  # enable the firebase project to be used for deployment.
  - firebase use --add $FIREBASE_DEPLOY_PROJECT_ID --alias default

## deployment stage.
deploy:
  # firebase deployment strategy.
  provider: firebase
  # skip cleanup so built artifacts are not lost.
  skip_cleanup: true
  # firebase authentication token.
  token: $FIREBASE_TOKEN
  # project id
  project: $FIREBASE_DEPLOY_PROJECT_ID
  # deployments for master branch only (production).
  on:
    branch: master
