language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
script: yarn build
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  message: $TRAVIS_BUILD_ID
