language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
script: yarn build
before_deploy:
  - npm install -g firebase-tools
  - firebase use --add $FIREBASE_DEPLOY_PROJECT --token $FIREBASE_TOKEN
deploy:
  provider: script
  script: firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
  on:
    branch: master
